np.sort
Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [3]:
import numpy as np

In [9]:
a = np.random.randint(1,100,15)
a

array([[41, 14, 81,  5, 75],
       [19, 81, 54, 35, 24],
       [ 2, 12,  1, 17,  7]])

In [11]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[30, 29, 70, 52],
       [18, 39,  4, 11],
       [79, 81, 99, 95],
       [52, 14, 98, 18],
       [93, 25, 25, 80],
       [99, 72, 43,  9]])

In [17]:
np.sort(a)[::-1]

array([[ 1,  2,  7, 12, 17],
       [19, 24, 35, 54, 81],
       [ 5, 14, 41, 75, 81]])

In [14]:
np.sort(b,axis=0)

array([[18, 14,  4,  9],
       [30, 25, 25, 11],
       [52, 29, 43, 18],
       [79, 39, 70, 52],
       [93, 72, 98, 80],
       [99, 81, 99, 95]])

np.append
The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [ ]:
# code

In [18]:
a 

array([[41, 14, 81,  5, 75],
       [19, 81, 54, 35, 24],
       [ 2, 12,  1, 17,  7]])

In [19]:
np.append(a,200)

array([ 41,  14,  81,   5,  75,  19,  81,  54,  35,  24,   2,  12,   1,
        17,   7, 200])

In [22]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[30., 29., 70., 52.,  1.],
       [18., 39.,  4., 11.,  1.],
       [79., 81., 99., 95.,  1.],
       [52., 14., 98., 18.,  1.],
       [93., 25., 25., 80.,  1.],
       [99., 72., 43.,  9.,  1.]])

In [23]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[30.        , 29.        , 70.        , 52.        ,  0.43264647],
       [18.        , 39.        ,  4.        , 11.        ,  0.375497  ],
       [79.        , 81.        , 99.        , 95.        ,  0.49020592],
       [52.        , 14.        , 98.        , 18.        ,  0.3861014 ],
       [93.        , 25.        , 25.        , 80.        ,  0.87310827],
       [99.        , 72.        , 43.        ,  9.        ,  0.98593361]])

np.concatenate
numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [24]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [27]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

np.unique
With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [29]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
f = np.array([[1,2,3,1],[1,2,3,2]])
print(e)
print(f)

[1 1 2 2 3 3 4 4 5 5 6 6]
[[1 2 3 1]
 [1 2 3 2]]


In [31]:
np.unique(f)

array([1, 2, 3])

np.expand_dims
With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [36]:
#code

a = np.arange(5)
a.shape

(5,)

In [37]:
np.expand_dims(a,axis=0).shape


(1, 5)

In [38]:
np.expand_dims(a,axis=1).shape

(5, 1)

np.where
The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [41]:
a = np.random.randint(1,100,15)
np.where(a>50)

(array([ 4,  5,  7, 10, 13, 14]),)

In [43]:
# replace all values > 50 with 0

np.where(a>50,0,a)

array([27, 17, 42, 40,  0,  0,  6,  0, 10, 49,  0, 17, 45,  0,  0])

In [44]:
np.where(a%2==0,0,a)

array([27, 17,  0,  0,  0, 81,  0,  0,  0, 49, 55, 17, 45,  0,  0])

np.argmax
The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [46]:
np.argmax(a)

7

In [49]:
b

array([[30, 29, 70, 52],
       [18, 39,  4, 11],
       [79, 81, 99, 95],
       [52, 14, 98, 18],
       [93, 25, 25, 80],
       [99, 72, 43,  9]])

In [50]:
np.argmax(b,axis=1)

array([2, 1, 2, 2, 0, 0])

In [51]:
np.argmax(b,axis=1)

array([2, 1, 2, 2, 0, 0])

In [52]:
np.argmin(a)

6

np.cumsum
numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [54]:
a

array([27, 17, 42, 40, 66, 81,  6, 88, 10, 49, 55, 17, 45, 64, 68])

In [55]:
np.cumsum(a)

array([ 27,  44,  86, 126, 192, 273, 279, 367, 377, 426, 481, 498, 543,
       607, 675])

In [56]:
b

array([[30, 29, 70, 52],
       [18, 39,  4, 11],
       [79, 81, 99, 95],
       [52, 14, 98, 18],
       [93, 25, 25, 80],
       [99, 72, 43,  9]])

In [57]:
np.cumsum(b)

array([  30,   59,  129,  181,  199,  238,  242,  253,  332,  413,  512,
        607,  659,  673,  771,  789,  882,  907,  932, 1012, 1111, 1183,
       1226, 1235])

In [59]:
np.cumsum(b,axis=1)

array([[ 30,  59, 129, 181],
       [ 18,  57,  61,  72],
       [ 79, 160, 259, 354],
       [ 52,  66, 164, 182],
       [ 93, 118, 143, 223],
       [ 99, 171, 214, 223]])

In [61]:
np.cumproduct(a)

array([                  27,                  459,                19278,
                     771120,             50893920,           4122407520,
                24734445120,        2176631170560,       21766311705600,
           1066549273574400,    58660210046592000,   997223570792064000,
        7981572538223776768, -5688191617545732096,   584595554790801408])

np.percentile
numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

X-axis=0 and Y-axis=1

In [60]:
a

array([27, 17, 42, 40, 66, 81,  6, 88, 10, 49, 55, 17, 45, 64, 68])

In [66]:
np.percentile(a,0)

6.0

In [67]:
np.percentile(a,50)

45.0

In [68]:
np.median(a)

45.0

np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [69]:
#code

a

array([27, 17, 42, 40, 66, 81,  6, 88, 10, 49, 55, 17, 45, 64, 68])

In [71]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 3, 1, 0, 4, 1, 3, 0, 2, 0]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [72]:
np.histogram(a,bins=[0,50,100])

(array([9, 6]), array([  0,  50, 100]))

np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [73]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

In [75]:
np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [76]:
a

array([27, 17, 42, 40, 66, 81,  6, 88, 10, 49, 55, 17, 45, 64, 68])

In [82]:
x = np.arange(0,100,10)
x
a[np.isin(x,a)]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 15 but corresponding boolean dimension is 10

np.flip
The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [83]:
a

array([27, 17, 42, 40, 66, 81,  6, 88, 10, 49, 55, 17, 45, 64, 68])

In [84]:
np.flip(a)

array([68, 64, 45, 17, 55, 49, 10, 88,  6, 81, 66, 40, 42, 17, 27])

In [85]:
np.flip(b)

array([[ 9, 43, 72, 99],
       [80, 25, 25, 93],
       [18, 98, 14, 52],
       [95, 99, 81, 79],
       [11,  4, 39, 18],
       [52, 70, 29, 30]])

np.put
The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [89]:
#code
a

array([110, 503,  42,  40,  66,  81,   6,  88,  10,  49,  55,  17,  45,
        64,  68])

In [88]:
np.put(a,[0,1],[110,503])

np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [92]:
asx = np.arange(10)

np.delete(asx,0)

asx


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Set functions

np.union1d
np.intersect1d
np.setdiff1d
np.setxor1d
np.in1d

In [93]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [94]:
np.intersect1d(m,n)

array([3, 4, 5])

In [95]:
np.setdiff1d(m,n)

array([1, 2])

In [96]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [97]:
np.in1d(m,n)

array([False, False,  True,  True,  True])

In [98]:
m[np.in1d(m,1)]

array([1])

np.clip
numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [99]:
a

array([110, 503,  42,  40,  66,  81,   6,  88,  10,  49,  55,  17,  45,
        64,  68])

In [102]:
np.clip(a,a_max=75,a_min=25)

array([75, 75, 42, 40, 66, 75, 25, 75, 25, 49, 55, 25, 45, 64, 68])

In [1]:
print('hello')

hello
