In [17]:
import numpy as np

Numpy array vs Python lists

In [16]:
# Speed
# list
import time

a = [i for i in range(10000000)]

b = [i for i in range(10000000,20000000)]

c = []
start = time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])
print(time.time()-start)


2.3262431621551514


In [21]:
# numpy
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a + b
print(time.time()-start)

0.12743258476257324


In [23]:
# memory
import sys

a = [i for i in range(10000000)]
sys.getsizeof(a)

81528048

In [27]:
a = np.arange(10000000,dtype='int32')
sys.getsizeof(a)

40000112

In [8]:
# convenience

Advanced Indexing

In [ ]:
# Normal Indexing and slicing

In [29]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
a[1][2]

5

In [31]:
a[1:3,1:3]

array([[4, 5],
       [7, 8]])

In [ ]:
# Fancy Indexing

In [32]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [37]:
a[[0,2,3]]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [36]:
aa = np.arange(24).reshape(6,4)

In [38]:
aa

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [39]:
aa[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [40]:
# Boolean Indexing
import numpy as np
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[59, 44, 11, 69],
       [63, 84, 42,  4],
       [54, 70, 65, 99],
       [74, 62, 29, 20],
       [ 5, 57, 88, 51],
       [43, 82, 80, 73]])

In [41]:
a > 50

array([[ True, False, False,  True],
       [ True,  True, False, False],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False,  True,  True,  True],
       [False,  True,  True,  True]])

In [43]:
# find all numbers greater than 50
a[a>50]

array([59, 69, 63, 84, 54, 70, 65, 99, 74, 62, 57, 88, 51, 82, 80, 73])

In [47]:
# find all numbers greater than 50 and are even
a[(a > 50) & (a & 2 == 0)]


array([69, 84, 65, 57, 88, 80, 73])

In [ ]:
# find all numbers greater than 50
a[a % 2 == 0]

In [48]:
# find all numbers not divisible by 7

a[a % 7 == 0]

array([63, 84, 42, 70])

In [49]:
a[a % 7 != 0]

array([59, 44, 11, 69,  4, 54, 65, 99, 74, 62, 29, 20,  5, 57, 88, 51, 43,
       82, 80, 73])

In [50]:
a[~(a % 7 == 0)]

array([59, 44, 11, 69,  4, 54, 65, 99, 74, 62, 29, 20,  5, 57, 88, 51, 43,
       82, 80, 73])

Broadcasting

The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

The smaller array is “broadcast” across the larger array so that they have compatible shapes.

In [52]:
# same shape
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [53]:
# diff shape
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


In [58]:
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a)
print()
print(b)

print()

print(a+b)

[[0 1 2]
 [3 4 5]]

[[0 1 2]]

[[0 2 4]
 [3 5 7]]


Broadcasting Rules
1. Make the two arrays have the same number of dimensions.

If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.

2. Make each dimension of the two arrays the same size.

If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.