
What is numpy?


NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

Numpy Arrays Vs Python Sequences

NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

Creating Numpy Arrays

In [1]:
# np.array
import numpy as np

In [8]:
#2D and 3D

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [7]:
# dtype
type(a)

numpy.ndarray

In [11]:
#Matrix
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [16]:
#Tensor
c = np.array([[[[1,2],[3,4]],[[5,6],[7,8]]]])
print(c)

[[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]]


In [17]:
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [47]:
for i in range(1,11):
    a = np.arange(i)
    print(a)

[0]
[0 1]
[0 1 2]
[0 1 2 3]
[0 1 2 3 4]
[0 1 2 3 4 5]
[0 1 2 3 4 5 6]
[0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8 9]


In [25]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [29]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [31]:
# np.ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
#np.random
np.random.random((3,4))

array([[0.59430693, 0.78824926, 0.07406498, 0.10668647],
       [0.19435757, 0.27185078, 0.33697341, 0.32351591],
       [0.2580627 , 0.35859812, 0.13685251, 0.87664753]])

In [40]:
#np.linspace
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [42]:
#np.identity

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Attributes

In [53]:
a1 = np.arange(10) # vector
a2 = np.arange(12,dtype=float).reshape(3,4) #Matrix
a3 = np.arange(8).reshape(2,2,2) #tensor

In [55]:
#ndim

a1.ndim

1

In [56]:
a2.ndim

2

In [57]:
a3.ndim

3

In [ ]:
#shape

In [58]:
a1.shape

(10,)

In [59]:
a2.shape

(3, 4)

In [60]:
a3.shape

(2, 2, 2)

In [61]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [62]:
#size
a3.size

8

In [64]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [63]:
a2.size

12

In [65]:
#itemsize
a1.itemsize

8

In [66]:
a3.itemsize

8

In [70]:
#dtype
print(a1.dtype)
print(a2.dtype)

int64
float64


Changing Datatype

In [73]:
#astype

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [76]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

Array Operations

In [78]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [80]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [79]:
#Scalar Operations

# arithmetic

a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [81]:
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [82]:
a2*2

array([[24, 26, 28, 30],
       [32, 34, 36, 38],
       [40, 42, 44, 46]])

In [86]:
#relational operations

a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [88]:
a2 != 15

array([[ True,  True,  True, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [89]:
#Vector Operations

#arithmetic

a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

Array function

In [96]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[31., 45., 28.],
       [87., 66., 24.],
       [63., 89., 66.]])

In [97]:
# max/min/sum/prod

np.max(a1)

89.0

In [98]:
np.min(a1)

24.0

In [99]:
np.sum(a1)

499.0

In [95]:
np.prod(a1)

0.0

In [100]:
# 0 -> col and row is ->1
np.max(a1,axis=1)

array([45., 87., 89.])

In [101]:
# mean/median/std/var

np.mean(a1,axis=1)

array([34.66666667, 59.        , 72.66666667])

In [102]:
np.median(a1,axis=1)

array([31., 66., 66.])

In [103]:
# trigonomoetric functions

np.sin(a1)

array([[-0.40403765,  0.85090352,  0.27090579],
       [-0.82181784, -0.02655115, -0.90557836],
       [ 0.1673557 ,  0.86006941, -0.02655115]])

In [108]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [110]:
# log and exponents

np.log(a1)
np.exp(a2)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [114]:
# round/floor/ceil

np.round(np.random.random((2,3))*100)

array([[ 0., 92., 81.],
       [59., 64., 26.]])

In [115]:
np.ceil(np.random.random((2,3))*100)

array([[85., 92., 44.],
       [32., 83., 24.]])

In [116]:
np.floor(a1)

array([[31., 45., 28.],
       [87., 66., 24.],
       [63., 89., 66.]])

Indexing and Slicing

In [117]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [123]:
a1[-1]

9

In [121]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [122]:
a2[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [124]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [127]:
a2[2][-1]

11

In [128]:
a2[2,-1]

11

In [129]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [133]:
a3[1][1][1]

7

In [134]:
a3[0,1,0]

2

In [136]:
a3[0,0,0]

0

In [137]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [139]:
a1[2:5]

array([2, 3, 4])

In [140]:
a1[2:5:2]

array([2, 4])

In [142]:
a2[0]

array([0, 1, 2, 3])

In [144]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [143]:
a2[:,2]

array([ 2,  6, 10])

In [146]:
a2[:,-1]

array([ 3,  7, 11])

In [148]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [149]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [152]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [161]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [165]:
a2[1,::3]

array([4, 7])

In [166]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [170]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])